/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation
import dk.sdu.mmmi.mdsd.math.Variable
import org.eclipse.xtext.diagnostics.Diagnostic
import dk.sdu.mmmi.mdsd.math.MathPackage.Literals
import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.VariableReference

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
	@Check
	def checkNoSelfReference(VariableReference reference) {
		val declaredVariable = reference.eContainer as Variable
		if (reference.variable.name.equals(declaredVariable.name)) {
			error('A variable cannot reference itself', Literals.VARIABLE_REFERENCE__VARIABLE, Diagnostic.LINKING_DIAGNOSTIC)
		}
	}
	
}
